# Generated by Django 3.2 on 2022-12-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Orange', ' Orange'), ('Green', 'Green')], max_length=100, null=True),
        ),
    ]
